### ISSUE TITLE
docker-compose.yml 란?

### ISSUE THREAD

**Issue by khseon7** [khseon7/Docker-practice#3]
`docker-compose`란 여러 개의 컨테이너로 구성된 애플리케이션을 쉽게 관리할 수 있도록 도와주는 도구로, `docker-compose.yml` 파일은 `docker-compose` 명령어를 사용하기 위해 컨테이너들을 정의한 파일로, 기본 구조는 다음과 같다.

### docker-compose.yml
``` yaml
version: '3'
services:
  django_pj:
    build: .
    volumes:
      - .:/django_pj
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    container_name: django-app
```

**Comment by khseon7** [comment]
### docker-compose 명령어
우리가 기초적으로 사용할 명령어는 `docker-compose up (-d)`, `docker-compose stop`, `docker-compose down`이다.

docker-compose up (-d)
- `docker-compose.yml` 파일을 기반으로 정의된 컨테이너들을 생성하고 실행한다. -d 옵션을 사용하면 백그라운드에서 실행된다.

docker-compose stop
- 실행 중인 컨테이너들을 정지한다.
- 이때 컨테이너들은 삭제되지 않고 유지된다.

docker-compose down
- 실행 중인 컨테이너를 중지하고, 네트워크 및 볼륨을 포함한 모든 관련 리소스를 제거한다.

**Comment by khseon7** [comment]
`docker-compose.yml`의 설정을 덮어쓰거나 추가할 때는 `docker-compose.override.yml` 파일을 사용할 수 있다. 이를 활용하면 기본 설정을 유지하면서 각자의 환경에 맞게 쉽게 변경할 수 있다. 또한, `docker-compose.override.yml`은 개발 환경에서만 사용하는 경우가 많아 Git에 올리지 않도록 `.gitignore`에 추가하는 것이 좋다.

**Comment by khseon7** [comment]
최근엔 `docker-compose start`를 사용했을 때 `the attribute version is obsolete, it will be ignored, please remove it to avoid potential confusion`라는 문구가 뜨는 것을 볼 수 있는데 이는 `version`이라는 속성이 구식이라 제거해도 된다는 것이니 이를 적용하여 `docker-compose.yml` 파일을 다음과 같이 수정할 수 있다.
### 수정된 docker-compose.yml 파일
``` yaml
services:
  django_pj:
    build: .
    volumes:
      - .:/django_pj
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    container_name: django-app
```
